# Copyright (c) 2024–2025 Kumar Aakash. Released under the MIT License.

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hintzcompiler"
version = "0.1.0"
description = "Hintz Compiler"
readme = "docs/IR.md"
requires-python = ">=3.10"
dependencies = [
  "lark>=1.1.5",
  "graphviz>=0.20",
  "flask>=2.2",
]

[project.scripts]
hintz = "hintzCompiler.compiler:main"

[tool.setuptools]
include-package-data = true
packages = ["hintzCompiler", "hintzCompiler.src"]
package-dir = { "hintzCompiler" = ".", "hintzCompiler.src" = "src" }

[tool.setuptools.package-data]
hintzCompiler = [
  "grammar/*.lark",
  "hintz_web/templates/*.html",
  "hintz_web/static/*",
]
